# Generated by Django 3.1.4 on 2023-02-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20230223_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo'),
        ),
    ]
