# Generated by Django 3.1.4 on 2023-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
