# Generated by Django 3.1.4 on 2023-02-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20230203_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
    ]
