# Generated by Django 3.1.4 on 2023-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20230223_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static/images/', verbose_name='Photo'),
        ),
    ]
