# Generated by Django 4.1.7 on 2023-02-27 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_alter_lead_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='document',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lead_cat', to='leads.category'),
            preserve_default=False,
        ),
    ]
