# Generated by Django 4.1.7 on 2023-03-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/agents', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='agent',
            name='position',
            field=models.CharField(blank=True, default='employee', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/leads', verbose_name='Photo'),
        ),
    ]
