# Generated by Django 4.1.7 on 2023-04-06 13:35

from django.db import migrations, models
import leads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_remove_agent_phone_number_remove_agent_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/', validators=[leads.validators.validate_file], verbose_name=models.CharField(max_length=200, unique=True)),
        ),
    ]
