# Generated by Django 4.1.7 on 2023-05-14 10:55

from django.db import migrations, models
import leads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_leadcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/', validators=[leads.validators.validate_file]),
        ),
    ]
